CREATE DATABASE brawlstars;
USE brawlstars;

CREATE TABLE ranking (
    tag VARCHAR(20) NOT NULL,
    name VARCHAR(40),
    nameColor VARCHAR(20),
    trophies INT,
    ranked INT,
    PRIMARY KEY (tag)
);

CREATE TABLE battlelog (
  battleTime varchar(45) NOT NULL,
  evnetId varchar(45),
  mode varchar(45) NOT NULL,
  map varchar(45) NOT NULL,
  type varchar(45) NOT NULL,
  result varchar(45) NOT NULL,
  duration varchar(45),
  trophyChange varchar(45),
  starPlayer_tag varchar(45),
  starPlayer_brawler_id varchar(45),
  starPlayer_brawler_name varchar(45),
  starPlayer_brawler_power varchar(45),
  starPlayer_brawler_trophies INT,
  player1_tag varchar(45),
  player1_name varchar(45),
  player1_brawler_id varchar(45),
  player1_brawler_name varchar(45),
  player1_brawler_power varchar(45),
  player1_brawler_trophies INT,
  player2_tag varchar(45),
  player2_name varchar(45),
  player2_brawler_id varchar(45),
  player2_brawler_name varchar(45),
  player2_brawler_power varchar(45),
  player2_brawler_trophies INT,
  player3_tag varchar(45),
  player3_name varchar(45),
  player3_brawler_id varchar(45),
  player3_brawler_name varchar(45),
  player3_brawler_power varchar(45),
  player3_brawler_trophies INT,
  player4_tag varchar(45),
  player4_name varchar(45),
  player4_brawler_id varchar(45),
  player4_brawler_name varchar(45),
  player4_brawler_power varchar(45),
  player4_brawler_trophies INT,
  player5_tag varchar(45),
  player5_name varchar(45),
  player5_brawler_id varchar(45),
  player5_brawler_name varchar(45),
  player5_brawler_power varchar(45),
  player5_brawler_trophies INT,
  player6_tag varchar(45),
  player6_name varchar(45),
  player6_brawler_id varchar(45),
  player6_brawler_name varchar(45),
  player6_brawler_power varchar(45),
  player6_brawler_trophies INT
);