CREATE DATABASE brawlstars;
USE brawlstars;

CREATE TABLE ranking (
    tag VARCHAR(20) NOT NULL,
    name VARCHAR(45),
    nameColor VARCHAR(20),
    trophies INT,
    ranked INT,
    PRIMARY KEY (tag)
);

CREATE TABLE battlelog (
    battleTime VARCHAR(45) NOT NULL,
    evnetId INT,
    eventMode VARCHAR(45) NOT NULL,
    map VARCHAR(45) NOT NULL,
    battleMode VARCHAR(45) NOT NULL,
    type VARCHAR(20) NOT NULL,
    result VARCHAR(20) NOT NULL,
    duration INT,
    trophyChange INT,
    starPlayer_tag VARCHAR(20),
    starPlayer_name VARCHAR(45),
    starPlayer_brawler_id INT,
    starPlayer_brawler_name VARCHAR(45),
    starPlayer_brawler_power INT,
    starPlayer_brawler_trophies INT,
    player1_tag VARCHAR(20),
    player1_name VARCHAR(45),
    player1_brawler_id INT,
    player1_brawler_name VARCHAR(45),
    player1_brawler_power INT,
    player1_brawler_trophies INT,
    player2_tag VARCHAR(20),
    player2_name VARCHAR(45),
    player2_brawler_id INT,
    player2_brawler_name VARCHAR(45),
    player2_brawler_power INT,
    player2_brawler_trophies INT,
    player3_tag VARCHAR(20),
    player3_name VARCHAR(45),
    player3_brawler_id INT,
    player3_brawler_name VARCHAR(45),
    player3_brawler_power INT,
    player3_brawler_trophies INT,
    player4_tag VARCHAR(20),
    player4_name VARCHAR(45),
    player4_brawler_id INT,
    player4_brawler_name VARCHAR(45),
    player4_brawler_power INT,
    player4_brawler_trophies INT,
    player5_tag VARCHAR(20),
    player5_name VARCHAR(45),
    player5_brawler_id INT,
    player5_brawler_name VARCHAR(45),
    player5_brawler_power INT,
    player5_brawler_trophies INT,
    player6_tag VARCHAR(20),
    player6_name VARCHAR(45),
    player6_brawler_id INT,
    player6_brawler_name VARCHAR(45),
    player6_brawler_power INT,
    player6_brawler_trophies INT,
    playerTag VARCHAR(20) NOT NULL,
    PRIMARY KEY (playerTag , battleTime)
);

select * from ranking;
select * from battlelog;

drop table ranking;
drop table battlelog;



CREATE TABLE battlelog (
    battleTime VARCHAR(45) NOT NULL,
    event_id INT,
    event_mode VARCHAR(45) NOT NULL,
    event_map VARCHAR(45) NOT NULL,
    battle_mode VARCHAR(45) NOT NULL,
    battle_type VARCHAR(20) NOT NULL,
    battle_result VARCHAR(20) NOT NULL,
    battle_duration INT,
    battle_trophyChange INT,
    battle_starPlayer_tag VARCHAR(20),
    battle_starPlayer_name VARCHAR(45),
    battle_starPlayer_brawler_id INT,
    battle_starPlayer_brawler_name VARCHAR(45),
    battle_starPlayer_brawler_power INT,
    battle_starPlayer_brawler_trophies INT,
    battle_teams_0_0_tag VARCHAR(20),
    battle_teams_0_0_name VARCHAR(45),
    battle_teams_0_0_brawler_id INT,
    battle_teams_0_0_brawler_name VARCHAR(45),
    battle_teams_0_0_brawler_power INT,
    battle_teams_0_0_brawler_trophies INT,
    battle_teams_0_1_tag VARCHAR(20),
    battle_teams_0_1_name VARCHAR(45),
    battle_teams_0_1_brawler_id INT,
    battle_teams_0_1_brawler_name VARCHAR(45),
    battle_teams_0_1_brawler_power INT,
    battle_teams_0_1_brawler_trophies INT,
    battle_teams_0_2_tag VARCHAR(20),
    battle_teams_0_2_name VARCHAR(45),
    battle_teams_0_2_brawler_id INT,
    battle_teams_0_2_brawler_name VARCHAR(45),
    battle_teams_0_2_brawler_power INT,
    battle_teams_0_2_brawler_trophies INT,
	battle_teams_1_0_tag VARCHAR(20),
    battle_teams_1_0_name VARCHAR(45),
    battle_teams_1_0_brawler_id INT,
    battle_teams_1_0_brawler_name VARCHAR(45),
    battle_teams_1_0_brawler_power INT,
    battle_teams_1_0_brawler_trophies INT,
    battle_teams_1_1_tag VARCHAR(20),
    battle_teams_1_1_name VARCHAR(45),
    battle_teams_1_1_brawler_id INT,
    battle_teams_1_1_brawler_name VARCHAR(45),
    battle_teams_1_1_brawler_power INT,
    battle_teams_1_1_brawler_trophies INT,
    battle_teams_1_2_tag VARCHAR(20),
    battle_teams_1_2_name VARCHAR(45),
    battle_teams_1_2_brawler_id INT,
    battle_teams_1_2_brawler_name VARCHAR(45),
    battle_teams_1_2_brawler_power INT,
    battle_teams_1_2_brawler_trophies INT,
    playerTag VARCHAR(20) NOT NULL,
    PRIMARY KEY (playerTag , battleTime)
);
